name: goggles-test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cython=0.29.22
  - matplotlib
  - scikit-image
  - black
  - isort
  - pytest
  - pyqt
  - pip
  - pip:
    - opencv-python
    - dearpygui